// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjMTRJZ7UZKGKWyArofcS8GgPYS9yKbUw',
    appId: '1:783751103329:web:b0ed32750da7958f843b20',
    messagingSenderId: '783751103329',
    projectId: 'rakshak-ee8d8',
    authDomain: 'rakshak-ee8d8.firebaseapp.com',
    storageBucket: 'rakshak-ee8d8.firebasestorage.app',
    measurementId: 'G-7GKD7QP82M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSwNHof1RvCJZRwmwLm8EffU24GxbXbwc',
    appId: '1:783751103329:android:2bd5bb7d3137acae843b20',
    messagingSenderId: '783751103329',
    projectId: 'rakshak-ee8d8',
    storageBucket: 'rakshak-ee8d8.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRXFUK5KGadMMG51p4birEypZSucoeIqs',
    appId: '1:783751103329:ios:b57d831f46961607843b20',
    messagingSenderId: '783751103329',
    projectId: 'rakshak-ee8d8',
    storageBucket: 'rakshak-ee8d8.firebasestorage.app',
    iosClientId: '783751103329-t51uihcj15kmt0pbis0qt0u7mr41108o.apps.googleusercontent.com',
    iosBundleId: 'com.example.rakshak',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRXFUK5KGadMMG51p4birEypZSucoeIqs',
    appId: '1:783751103329:ios:b57d831f46961607843b20',
    messagingSenderId: '783751103329',
    projectId: 'rakshak-ee8d8',
    storageBucket: 'rakshak-ee8d8.firebasestorage.app',
    iosClientId: '783751103329-t51uihcj15kmt0pbis0qt0u7mr41108o.apps.googleusercontent.com',
    iosBundleId: 'com.example.rakshak',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjMTRJZ7UZKGKWyArofcS8GgPYS9yKbUw',
    appId: '1:783751103329:web:fdaffdaac7b9946c843b20',
    messagingSenderId: '783751103329',
    projectId: 'rakshak-ee8d8',
    authDomain: 'rakshak-ee8d8.firebaseapp.com',
    storageBucket: 'rakshak-ee8d8.firebasestorage.app',
    measurementId: 'G-V8CCF1RW8T',
  );

}